backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "blog"
    label: "Bài viết"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Tóm tắt", name: "excerpt", widget: "text" }
      - { label: "Ảnh bìa", name: "cover_image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
